var mountains = ["Mount Everest", "Kilimanjaro", "Rocky Mountains", "Alps", "Andes"];
var rivers = ["Amazon River", "Nile River", "Ganges River", "Mississippi River", "Danube River"];
var countries = ["United States", "India", "Brazil", "China", "Australia"];
var cities = ["Tokyo", "Paris", "New York City", "Sydney", "Cairo"];
var languages = ["English", "Spanish", "Mandarin Chinese", "Hindi", "French"];
console.log(mountains);
console.log(rivers);
console.log(countries);
console.log(cities);
console.log(languages);
